Add Footer
dojo/dgrid pull request #25
Opened 2017-04-14 02:00 UTC by msssk

**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue: #11 
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

* Add a Footer module
    * The footer is not rendered by default. If the grid property `footerChildren` is specified then the footer will be rendered, and contain the provided children.
* Add a Footer example page
* Add Footer unit tests

NOTE: this branch is based off the [`initial` branch](https://github.com/pottedmeat/dgrid/tree/initial) so it should be merged after that.

2017-04-14 12:14 UTC, dylans commented
This PR appears to have a bunch of commits from February, probably needs a rebase @msssk.

2017-04-14 14:31 UTC, msssk commented
I didn't realize https://github.com/pottedmeat/dgrid/tree/initial wasn't based off master. It has some useful things in it, like an example page. I think we should get a foundation for example pages into master ASAP as it greatly facilitates development. It's a bit awkward developing off of current master since there's no environment to render what you're working on and see it working.

2017-04-18 05:03 UTC, msssk commented
This PR is now based on master.

2017-04-18 05:43 UTC, agubler reviewed
Have you thought about using the new harness from @dojo/test-extras for the unit tests.

2017-04-18 14:33 UTC, dylans commented
> Have you thought about using the new harness from @dojo/test-extras for the unit tests.

I don't think that's really been announced to the team as ready for general use yet, has it? I think for dgrid that would be awesome, but perhaps as a separate PR?

2017-04-18 14:35 UTC, dylans approved these changes
With the caveat that we will want to switch the test harness under a separate PR, I think this is great and should land.

2017-04-18 14:50 UTC, pottedmeat requested changes

2017-04-18 14:50 UTC, pottedmeat commented on src/Footer.ts
> +import { RegistryMixin, RegistryMixinProperties }  from '@dojo/widget-core/mixins/Registry';
I think there's an extra space before `from`

2017-04-18 14:50 UTC, pottedmeat commented on src/styles/footer.m.css
> +	position: absolute;
Grid styling won't require things to be absolutely positioned, etc. the way they were in dgrid1. We should be able to remove bottom/position rules (see https://github.com/dojo/dgrid/issues/13)

2017-04-28 16:08 UTC, pottedmeat approved these changes

2017-04-29 04:40 UTC, merged