Add examples folder and HTML page
dojo/dgrid pull request #29
Opened 2017-04-28 17:54 UTC by msssk

The `examples/index.html` page can be used for all examples.

To create an example page:
* create a TypeScript file in the `examples` folder that creates a projector and appends it to the document.
* add a link to it in `ul#links` in `index.html`

Run `grunt dev` and open `_build/examples/index.html` in your browser. You should see a list of links to test pages.

2017-04-28 17:56 UTC, msssk commented
An enhancement to consider:

Add `paths` config to `tsconfig.json` so that in example files we can use package imports, instead of relative imports, e.g.:

```typescript
import Grid from 'dgrid/Grid';
// instead of
import Grid from '../../src/Grid';
```

2017-04-28 18:00 UTC, pottedmeat commented on Gruntfile.js
> +            examples: {
Should this be called staticExampleFiles like in widgets?

2017-04-28 18:01 UTC, pottedmeat requested changes

2017-04-28 18:01 UTC, pottedmeat commented on Gruntfile.js
> +            examples: {
I also think this needs to be added to the dev task

2017-04-28 18:05 UTC, pottedmeat commented on examples/index.html
> +		<li><a href="?module=pagination">Pagination</a></li>
Should just comment this out for now

2017-04-28 22:13 UTC, msssk commented on Gruntfile.js
> +            examples: {
> Should this be called staticExampleFiles like in widgets?

I think we're fine inlining static values that are specific to the dgrid project, as is already being done just above for `devStyles.src` and `distStyles.src`.

2017-04-28 22:14 UTC, msssk commented on Gruntfile.js
> +            examples: {
> I also think this needs to be added to the dev task

Do we also want to include examples in dist?

2017-04-29 02:39 UTC, pottedmeat approved these changes

2017-04-29 04:38 UTC, merged