Customizable Headers and Footers, fixes #11
dojo/dgrid pull request #38
Opened 2017-05-24 20:30 UTC by pottedmeat

**Type:** feature

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

* Header => ColumnHeaders
* HeaderCell => ColumnHeaderCell
* Adds Header as a general-purpose wrapper, like footer
* Adds headers/footers as grid properties to allow custom children
* Provides an enum to indicate you want column headers in the header or footer area

2017-05-25 02:49 UTC, msssk approved these changes

2017-05-25 02:49 UTC, msssk commented on src/ColumnHeaders.ts
> +import { ThemeableMixin, theme, ThemeableProperties } from '@dojo/widget-core/mixins/Themeable';
`theme` should be first

2017-05-26 06:15 UTC, kitsonk requested changes

2017-05-26 06:15 UTC, kitsonk commented on src/Grid.ts
> +	footers?: Array<HeaderType | DNode>;
generally we use `(HeaderType | DNode)[]`

2017-05-26 06:15 UTC, kitsonk commented on src/Grid.ts
> +			}, <DNode[]> headers.map((child) => {
Seems odd we need a cast here.  Also this logic is quite hard to follow in line and is duplicated below.  This should probably be broken into a function that is easier to grok and maintain.

2017-05-30 13:49 UTC, kitsonk approved these changes

2017-06-06 21:39 UTC, merged