On Demand Scrolling
dojo/dgrid pull request #39
Opened 2017-05-30 15:49 UTC by pottedmeat

**Type:** feature

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Resolves #21 

This introduces the slice API to data providers to request the data only contain a subsection of the currently available data the provider would otherwise return (including sorts etc.)

The grid body makes a slice request to the data provider that will contain enough data to fill the content area as well as buffer rows above and below it.

As rows are added and removed from the grid, their heights are factored into the scroll position of the scrollable area to ensure that as the size of the scrollable content changes, the scroll position remains at the same position within the visible content.

It adds a large margin before and after the content area so that rapid scrolling won't "hit an edge".

If scrolling is done so rapidly that the user ends up outside the buffer rows, the grid body estimates how far it has been scrolled beyond the buffer rows, makes a slice for that data, and scrolls to the estimated row.

Users can also define what index to scroll the data to through a grid property.

2017-05-30 21:45 UTC, dylans requested changes
Two minor nits (my review focused on comments rather than the code logic)

2017-05-30 21:45 UTC, dylans commented on src/Grid.ts
> +import {  DataProperties, HasBufferRows,  HasColumns, HasScrollTo, ScrollToDetails, SliceRequestListener,  SortRequestListener } from './interfaces';
Looks like some unintentional double spaces in here.

2017-05-30 21:45 UTC, dylans commented on src/bases/DataProviderBase.ts
> +	 * otherwise. Can also be assigned from
assigned from ... ?

2017-05-31 05:40 UTC, maier49 commented on src/Body.ts
> +		for (let details of from(itemElementMap.values())) {
Does itemElementMap contain collapsed rows in a tree scenario, and would they have an element that could mess up the average height if that is the case? Not sure if we're even worried about tree stuff for this PR.

2017-06-01 05:24 UTC, msssk approved these changes
Some comments inline, overall looks good.

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +			w<Row>('row', {
Why is it necessary to wrap each row in a `div`?

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +	protected estimatedRowHeight(): number {
Might be better if this is a property with `get` defined, or rename the method to `getEstimatedRowHeight`

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +	protected estimatedRowCount(): number {
Might be better if this is a property with `get` defined, or rename the method to `getEstimatedRowCount`

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +		for (let details of from(itemElementMap.values())) {
A pain point I discovered in working with this same logic in dgrid 1 is that browsers do not always give reliable information about element dimensions, most notably when there is any scaling in effect (e.g. a high dpi display with OS-provided scaling, or zoom level set in the browser).

Inspecting a node in the dev tools would give a non-integer value, e.g. 25.57, whereas `element.offsetHeight` would report 25. This error accumulated over a large number of rows results in significant height discrepancies. I found it more accurate to get height values directly from the node containing all the rows, rather than summing up the heights of each individual row.

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +import { from, includes } from '@dojo/shim/array';
Have we developed any standard for this? Had any discussion? Personally I rather dislike importing and calling `from` directly. It doesn't make for clear code. I'd prefer:
`array.from`
or
`import { from as toArray } from '@dojo/shim/array';`

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +			let cleared = true;
I think I'm following the logic here, but could `cleared` benefit from a more descriptive name?

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +		const max = (dataLength > 0 ? dataLength - 1 : 0);
`max` what? Could this benefit from a more descriptive name?

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +	protected visibleKeys() {
Might be better if this is a property with `get` defined, or rename the method to `getVisibleKeys`

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +			for (const renderedDetails of allDetails.reverse()) {
Might calling `reverse` impact performance?

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +		const max = (dataLength > 0 ? dataLength - 1 : 0);
`max` what? Could this benefit from a more descriptive name?

2017-06-01 05:24 UTC, msssk commented on src/Body.ts
> +			for (let i = 0, il = previousKeys.length; i <= il; i++) {
Can we use a more descriptive name than `il`? Perhaps `i` as well given the length and complexity of this loop.

2017-06-01 05:24 UTC, msssk commented on src/interfaces.d.ts
> +	 * @default 10
This seems like not the right place to document default values - is it possible to document them in the right place and get the right generated doc output?

2017-06-29 22:09 UTC, closed without merging